services:
  manna-server:
    image: ghcr.io/${GITHUB_OWNER}/manna-backend:latest
    container_name: manna-server
    restart: always
    ports:
      - 4030:4030
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=prod

  nginx:
    image: nginx:latest
    container_name: manna-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - manna-server
